# -*- coding: utf-8 -*-
"""webScraping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ba7mL1G8jW9jmwreINeLRB6yGUnkk4eG

# **Image Scraping** :

**Library used :**  BeautifulSoup , Requests




---
**INPUTS & USEAGE** 

<br/>

**URL :** enter the URL from  which images are to be downloaded
<br/>
**PATH :** enter the path which is basically the url after the base url

EX.  https: //example.com/data/index.html

URl = "https: //example.com"
PATH =  / data/index.html

Installing  requests and beautifulSoup4  library
"""

pip  install requests

pip  install  beautifulSoup4

"""Importing beautifulSoup and requests"""

#importing  libraries

import requests
from bs4 import  BeautifulSoup as bs

# declaring a  list  to store the images

resultImages = []

#  replace your url ( remember  this should be a  base url like : "www.example.com")

url = "http://bvucoepune.edu.in/"

# replace your path  ( should be of form : "/path-name")
# incase you are trying to access the homepage  leave  the path blank ""

path = ""

# making  requests to load the url

loader = requests.get(url + path)

# now  create the object of the beautifulscope 

obj = bs(loader.content)

# performing some  operations on  the object and filtering out the images

images = obj.find_all("img")

for image in  images:
  print(image.get("src"))